<header id="header">
    <h1>Astrea</h1>
    <img id="logo" src="/static/img/AstreaLogo.jpg" alt="Un logo con forma de balanza con alas">
</header>

<nav id="upperbar">
    <button id="pos1" onclick="redirigir('/index')">Inicio</button>
    <button id="pos2" onclick="redirigir('/mc-modpack')">Minecraft</button>
    <button id="pos3" onclick="redirigir('/satisfactory')">Satisfactory</button>
    <button id="pos4">espacio para pruebas</button>
</nav>
