<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Astrea</title>
    <link rel="stylesheet" href="../static/styles/default.css">
    <script src="/static/scripts/script.js"></script>
</head>

<body>
<div id="container">
    @template.header()

        <main>
            <section>
                <article>
                    <h2>Inicio</h2>
                    <p>Esta pagina web esta dedicada al servidor "Astrea". <br> Aqui podras encontrar archivos relacionados con los juegos que se hostean</p>
                </article>
            </section>
        </main>

        <footer>
            <h5>Direcciones de contacto:</h5>
            <h6>xipabloxon@gmail.com</h6>
        </footer>
    </div>
</body>

</html>