<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Astrea</title>
    <link rel="stylesheet" href="static/styles/default.css">
    <script src="static/scripts/script.js"></script>
</head>

<body>
<div id="container">
    @template.header()

    <main>
        <section>
            <article>
                <h2>Modpack</h2>
                <p>Desde aqui podras descargar el Modpack que estamos usando en el servidor.</p>
                <ul>
                    <li>&quot;(Last)&quot; es la ultima version del Modpack, la que el servidor esta usando.</li>
                    <li>&quot;Update&quot; solo contiene los archivos necesarios para actualizar el modpack desde la
                        versión anterior
                    </li>
                </ul>
            </article>
            <article>
                <p><a href="../archivos/mc-modpack/astreapack-ver5.zip">astreapack-ver5</a><span
                            class="sub">(Last)</span></p>
            </article>
        </section>
    </main>

    <footer>
        <h5>Direcciones de contacto:</h5>
        <h6>xipabloxon@gmail.com</h6>
    </footer>
</div>
</body>

</html>